name: Deploy to github pages

on:
  push:
    branches: [master]

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest

    name: Deploy to gh-pages
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Install project with a clean slate
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "reymon359" && git config user.email "ramonmorcillocascales@gmail.com"
          npm run deploy
